# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTrace < Formula
  desc "Instantly visualize request flows in your Go application — no infrastructure, no code changes."
  homepage "https://github.com/mickamy/go-trace"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.2/go-trace_0.0.2_darwin_amd64.tar.gz"
      sha256 "910042e89c5f95f5159ae1b528c7cd0b9ec67b38c88348d45c466f2ad7708ce5"

      define_method(:install) do
        bin.install "go-trace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.2/go-trace_0.0.2_darwin_arm64.tar.gz"
      sha256 "476b4f7f48523378a6ad398bfa567f715944a2d9ec5f2d149cec85c05710ec60"

      define_method(:install) do
        bin.install "go-trace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.2/go-trace_0.0.2_linux_amd64.tar.gz"
      sha256 "dbae01165870d26e58c6e3c0535c7ff9cde629d76997993885292929c78d4589"
      define_method(:install) do
        bin.install "go-trace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.2/go-trace_0.0.2_linux_arm64.tar.gz"
      sha256 "137c25439b4a984d0f969c22e0c0980aa50a776c6a5974664901282f9c90003c"
      define_method(:install) do
        bin.install "go-trace"
      end
    end
  end
end
