# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTrace < Formula
  desc "Instantly visualize request flows in your Go application — no infrastructure, no code changes."
  homepage "https://github.com/mickamy/go-trace"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.1/go-trace_0.0.1_darwin_amd64.tar.gz"
      sha256 "5fb9eae30f7ce45f418b5da214c2f15767e46999828a5af702a21bb119354346"

      define_method(:install) do
        bin.install "go-trace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.1/go-trace_0.0.1_darwin_arm64.tar.gz"
      sha256 "cf7c1e85efd97910a9aebe1fa04ed8af8351617ff4a24d339fa85aa1ec4c57ef"

      define_method(:install) do
        bin.install "go-trace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.1/go-trace_0.0.1_linux_amd64.tar.gz"
      sha256 "1685815dc4c706c55f028eb7f00406c05e48b17a4e2d255d94f5b18687e8bf08"
      define_method(:install) do
        bin.install "go-trace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.1/go-trace_0.0.1_linux_arm64.tar.gz"
      sha256 "f084c8840ca991a9fb6d43833f0de011d0b5957f379a91445512781f6ad32944"
      define_method(:install) do
        bin.install "go-trace"
      end
    end
  end
end
