# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrpcTap < Formula
  desc "Watch gRPC traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/grpc-tap"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.4/grpc-tap_0.0.4_darwin_amd64.tar.gz"
      sha256 "a136500982c471e7ae7420fe5617deb8fc754737e2b7f44fb3f26626b9a7d68b"

      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.4/grpc-tap_0.0.4_darwin_arm64.tar.gz"
      sha256 "3376d99ce801a50e01d9f76d5e47a622c9820c08a64e950a6fd2e8022efc40d2"

      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.4/grpc-tap_0.0.4_linux_amd64.tar.gz"
      sha256 "97292bfb88309beef319a2461d144dedd2182c4622861d9d4a51752c1cfb41fc"
      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.4/grpc-tap_0.0.4_linux_arm64.tar.gz"
      sha256 "bbe5cc8f93604ab4289ae20b4602d0de225017361933749424d76b5acf4433c1"
      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
  end
end
