# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrpcTap < Formula
  desc "Watch gRPC traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/grpc-tap"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.5/grpc-tap_0.0.5_darwin_amd64.tar.gz"
      sha256 "cd01c2e5165208d083522f53de6e82a3c6a1f9f5c6bb1ee584d5dfe1cacd69ff"

      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.5/grpc-tap_0.0.5_darwin_arm64.tar.gz"
      sha256 "b71f933b0dcd69bb40df782008ff8a926703c4ccce875639b726bdbdd6777971"

      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.5/grpc-tap_0.0.5_linux_amd64.tar.gz"
      sha256 "aef36e29fb451c82f518ed1fb9d70dcafab3a0ea2c8c8bf0a4facd58af9bfe10"
      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.5/grpc-tap_0.0.5_linux_arm64.tar.gz"
      sha256 "6de8742752bc190249cb7c65c538eb75b0947bc8943c22fba71e54a8b753999e"
      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
  end
end
