# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpTap < Formula
  desc "Watch HTTP traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/http-tap"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/http-tap/releases/download/v0.0.1/http-tap_0.0.1_darwin_amd64.tar.gz"
      sha256 "e8e9d5196d13b2bb1f90f26cf7f228e925174652319e7efc938ea89dfd5a078c"

      define_method(:install) do
        bin.install "http-tap"
        bin.install "http-tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/http-tap/releases/download/v0.0.1/http-tap_0.0.1_darwin_arm64.tar.gz"
      sha256 "56249ac9f49600243a1fceaba3a18b9288452e8326e778cdd47e799141f5b949"

      define_method(:install) do
        bin.install "http-tap"
        bin.install "http-tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/http-tap/releases/download/v0.0.1/http-tap_0.0.1_linux_amd64.tar.gz"
      sha256 "ffc5e7043e2075eef04edc9cba8bb7afd632c29f698c11b713a03610046ff8f0"
      define_method(:install) do
        bin.install "http-tap"
        bin.install "http-tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/http-tap/releases/download/v0.0.1/http-tap_0.0.1_linux_arm64.tar.gz"
      sha256 "6aae45f0e76eeec5f5ab248378aff9ab809cbca20db8e9e4fd967113ba08f2df"
      define_method(:install) do
        bin.install "http-tap"
        bin.install "http-tapd"
      end
    end
  end
end
