# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seeder < Formula
  desc "Populate your database with realistic fake data, one command."
  homepage "https://github.com/mickamy/seeder"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_darwin_amd64.tar.gz"
      sha256 "952ba4ff901d7b3f00f5eadb93cbd9ed74d15e3384834fa511fb0b86daadeb2a"

      define_method(:install) do
        bin.install "seeder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_darwin_arm64.tar.gz"
      sha256 "dcae0fc1402cb5d0d2a82a549cf76b98dd56563593769ba9f61b7584fe023a4a"

      define_method(:install) do
        bin.install "seeder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_linux_amd64.tar.gz"
      sha256 "df56d6d79380aacfbe5e5c6fcdb044d04221fc88284cd1ab5bd72b24ba83acce"
      define_method(:install) do
        bin.install "seeder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_linux_arm64.tar.gz"
      sha256 "0bd0e1843558a727d5ff7e7af64494da4e299d2cf2fea5720271f32e0fdb8c37"
      define_method(:install) do
        bin.install "seeder"
      end
    end
  end
end
