# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spretty < Formula
  desc "Pretty-printer for slog JSON logs — as a CLI pipe or slog.Handler"
  homepage "https://github.com/mickamy/slog-pretty"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/slog-pretty/releases/download/v0.0.1/slog-pretty_0.0.1_darwin_amd64.tar.gz"
      sha256 "398496d13def9cebf3b8949d8ec0a975c0b2ef54104a72e76a86f8b4c43c293c"

      define_method(:install) do
        bin.install "spretty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/slog-pretty/releases/download/v0.0.1/slog-pretty_0.0.1_darwin_arm64.tar.gz"
      sha256 "c020cb4b96adcd036f485fee80824dcad7f1c56a16f5fc194796559f6bcb11e9"

      define_method(:install) do
        bin.install "spretty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/slog-pretty/releases/download/v0.0.1/slog-pretty_0.0.1_linux_amd64.tar.gz"
      sha256 "bf21d2a3b3c5e02cf2ca416edd4ed10fd025d7ee7660e857bbe6d4adbd96e033"
      define_method(:install) do
        bin.install "spretty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/slog-pretty/releases/download/v0.0.1/slog-pretty_0.0.1_linux_arm64.tar.gz"
      sha256 "8d90b39947ab5424ac3724360981622998f95295131c12af0a4b38d6cd0ceea5"
      define_method(:install) do
        bin.install "spretty"
      end
    end
  end
end
