# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SqlTap < Formula
  desc "Watch SQL traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/sql-tap"
  version "0.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.2.8/sql-tap_0.2.8_darwin_amd64.tar.gz"
      sha256 "f58e1338e3e9b26e54262ececd701edbfd1ed66d12bd00f26b89c79641a9578f"

      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.2.8/sql-tap_0.2.8_darwin_arm64.tar.gz"
      sha256 "aca7ff91aac446cfc552ac3c8e8a716f7b0c651c065088cc8c3ecd19b0916ce7"

      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.2.8/sql-tap_0.2.8_linux_amd64.tar.gz"
      sha256 "93dab522219fc802c6eab2aef71c251e696e945933feb1ac0a822a7069008f52"
      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.2.8/sql-tap_0.2.8_linux_arm64.tar.gz"
      sha256 "4a50ff610d1d67e05e423ef0434226d580ea009cd01b7c55937c3f7724f79241"
      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
  end
end
