# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SqlTap < Formula
  desc "Watch SQL traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/sql-tap"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.0/sql-tap_0.3.0_darwin_amd64.tar.gz"
      sha256 "7e659eb8ce52f24a8af48b37f4a67cefd39aaf156a0f59bccd07f79cbab9689a"

      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.0/sql-tap_0.3.0_darwin_arm64.tar.gz"
      sha256 "ef85768f1310a52dcfcb8e222ad4de5e4806237e0241242541e7fd3028a5fe3d"

      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.0/sql-tap_0.3.0_linux_amd64.tar.gz"
      sha256 "d108a00b3238f2539b84157ba832dab869f8fcb50d51d7449c608598c11d556e"
      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.0/sql-tap_0.3.0_linux_arm64.tar.gz"
      sha256 "35b200b8a76aed166e02633e6d4481b1d24783cac2fa20fff6e61feb3139b817"
      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
  end
end
