# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapbox < Formula
  desc "A local dev tool that traces HTTP, gRPC, and SQL in a single view."
  homepage "https://github.com/mickamy/tapbox"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/tapbox/releases/download/v0.0.1/tapbox_0.0.1_darwin_amd64.tar.gz"
      sha256 "c82dcdcf43548d61eb68f0aa7146a9bdc1a0a8ec002d69b5b0129771f7cc241b"

      define_method(:install) do
        bin.install "tapbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/tapbox/releases/download/v0.0.1/tapbox_0.0.1_darwin_arm64.tar.gz"
      sha256 "13812e991609f18a2a6c17b6bf32b6995bf55dd43e4bb2364cf472384209c8f6"

      define_method(:install) do
        bin.install "tapbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tapbox/releases/download/v0.0.1/tapbox_0.0.1_linux_amd64.tar.gz"
      sha256 "7cff6fc7b85275f1cbf57987291e5b197d093a73a58f77d54b603d75164585dd"
      define_method(:install) do
        bin.install "tapbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tapbox/releases/download/v0.0.1/tapbox_0.0.1_linux_arm64.tar.gz"
      sha256 "aba3943e596ffd0bc112d2ab17e7b786b785b2426eefc464968d07b15b54ea68"
      define_method(:install) do
        bin.install "tapbox"
      end
    end
  end
end
