# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trc < Formula
  desc "A local request tracer for Docker microservices."
  homepage "https://github.com/mickamy/trc"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/trc/releases/download/v0.0.1/trc_0.0.1_darwin_amd64.tar.gz"
      sha256 "6a2e5bf5895308f24e2c3e26381bddead50e88d52aed468146c4fa6adc20d0b5"

      define_method(:install) do
        bin.install "trc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/trc/releases/download/v0.0.1/trc_0.0.1_darwin_arm64.tar.gz"
      sha256 "891dc44c7168e49b2969ac6a69f4baff54b65ec1c5d286403a879bb280fa7a50"

      define_method(:install) do
        bin.install "trc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/trc/releases/download/v0.0.1/trc_0.0.1_linux_amd64.tar.gz"
      sha256 "fbe3fe0098c549268c6746654e6183c870de5f7adc7a42bec612c7f1d36b2502"
      define_method(:install) do
        bin.install "trc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/trc/releases/download/v0.0.1/trc_0.0.1_linux_arm64.tar.gz"
      sha256 "de6a05098617c8384e6cd7cb9b7de162d71161ac98609ead164fab5eefb62695"
      define_method(:install) do
        bin.install "trc"
      end
    end
  end
end
