# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tug < Formula
  desc "Replace port conflicts with stable, named URLs for Docker Compose."
  homepage "https://github.com/mickamy/tug"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/tug/releases/download/v0.0.5/tug_0.0.5_darwin_amd64.tar.gz"
      sha256 "d4f90bbe7ac74e18347c3159f866b28c96eacfa51c37b84818c494154bbe5c78"

      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/tug/releases/download/v0.0.5/tug_0.0.5_darwin_arm64.tar.gz"
      sha256 "eb530eebf774d6f69083b1312e509a90036e0412fbef08422e9fc01807fbbe39"

      define_method(:install) do
        bin.install "tug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.5/tug_0.0.5_linux_amd64.tar.gz"
      sha256 "365ed611e087a01501c96fd2fcfc02b98858b49315047a49b3a5b6ce0ae4a097"
      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.5/tug_0.0.5_linux_arm64.tar.gz"
      sha256 "e9dd9fbe521537772192e0ca28e3944527cfc1d71b1216b519faa3e93839d7fe"
      define_method(:install) do
        bin.install "tug"
      end
    end
  end
end
