# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tug < Formula
  desc "Replace port conflicts with stable, named URLs for Docker Compose. For humans and agents."
  homepage "https://github.com/mickamy/tug"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/tug/releases/download/v0.0.1/tug_0.0.1_darwin_amd64.tar.gz"
      sha256 "adc9d3a9261e53ca3774be34c5347cc6da9238a1483b4de1ce6006c8656c8906"

      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/tug/releases/download/v0.0.1/tug_0.0.1_darwin_arm64.tar.gz"
      sha256 "abe3944230f5eee5bb8f5c4101cca334a36a3bd689acb58d637f0fd57f00e135"

      define_method(:install) do
        bin.install "tug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.1/tug_0.0.1_linux_amd64.tar.gz"
      sha256 "3f5346fe376a6253d5bcc36fb45072bcd65d2382e2d1c3af608687c6b566c9e9"
      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.1/tug_0.0.1_linux_arm64.tar.gz"
      sha256 "bde513fde612bb0a9e9ec494d89eaa2f09c7f1498199d0ff55c4e555374e634d"
      define_method(:install) do
        bin.install "tug"
      end
    end
  end
end
