# This file was generated by GoReleaser. DO NOT EDIT.
cask "grpc-tap" do
  name "grpc-tap"
  desc "Watch gRPC traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/grpc-tap"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grpc-tap"
  binary "grpc-tapd"

  on_macos do
    on_intel do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_darwin_amd64.tar.gz"
      sha256 "97108f0578257622b700af116c623e68632459d6f3794808d647d9e6de3fe549"
    end
    on_arm do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_darwin_arm64.tar.gz"
      sha256 "aa504f73a05526d6f5fadf3b5d6a169e85fc41ab460c5d88e8a9561ba88add7f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_linux_amd64.tar.gz"
      sha256 "22ac826bbea732c748f0599783a24feedb3f01076ec0fea59c48fa1da5f0f720"
    end
    on_arm do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_linux_arm64.tar.gz"
      sha256 "7bc7e06e25512c169f1799d88b180891cc79731baad78bca0bd5a69dc182cf8a"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
