# This file was generated by GoReleaser. DO NOT EDIT.
cask "grpc-tap" do
  name "grpc-tap"
  desc "Watch gRPC traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/grpc-tap"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grpc-tap"
  binary "grpc-tapd"

  on_macos do
    on_intel do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_darwin_amd64.tar.gz"
      sha256 "341558a09e4cba3f692e5f78cfa69b1d0759384b1d1b69841cb42ec9bc111891"
    end
    on_arm do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_darwin_arm64.tar.gz"
      sha256 "fe85db2a982ff2b5764551e39dcaaf73716f48b6328af4468ecbc803020c879c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_linux_amd64.tar.gz"
      sha256 "8bf3855895a1e33e39ccb50df70dd4a888afd340343342bc3e4a5c3c10519f4c"
    end
    on_arm do
      url "https://github.com/mickamy/grpc-tap/releases/download/v#{version}/grpc-tap_#{version}_linux_arm64.tar.gz"
      sha256 "c7be2a2da2f599cb84754eb425f34f5ba2d627fc4a8f37137a7a7b186a17109c"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
