# This file was generated by GoReleaser. DO NOT EDIT.
cask "sql-tap" do
  name "sql-tap"
  desc "Watch SQL traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/sql-tap"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sql-tap"
  binary "sql-tapd"

  on_macos do
    on_intel do
      url "https://github.com/mickamy/sql-tap/releases/download/v#{version}/sql-tap_#{version}_darwin_amd64.tar.gz"
      sha256 "2d681f14eb268beb605b7fd3f431cee86d182c90d20fea582c8e74937863f548"
    end
    on_arm do
      url "https://github.com/mickamy/sql-tap/releases/download/v#{version}/sql-tap_#{version}_darwin_arm64.tar.gz"
      sha256 "60ecdaf2f7cd1ce5a25853e7acff83c4170684ea48a894528e1af54a4ccf9891"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mickamy/sql-tap/releases/download/v#{version}/sql-tap_#{version}_linux_amd64.tar.gz"
      sha256 "aea05636aadf82f10e30adc859fd07d1e36d3ad76fc6200fd8fefb36d6e61781"
    end
    on_arm do
      url "https://github.com/mickamy/sql-tap/releases/download/v#{version}/sql-tap_#{version}_linux_arm64.tar.gz"
      sha256 "67e001a935301646da07bb696be73a81ecdee5c06dae62acf43c187b75783c0d"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
  end

  # No zap stanza required
end
