# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adms < Formula
  desc "PostgREST-style HTTP API for PostgreSQL and MySQL, plus an optional bundled admin UI — all in one binary."
  homepage "https://github.com/mickamy/adms"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/adms/releases/download/v0.0.1/adms_0.0.1_darwin_amd64.tar.gz"
      sha256 "8024b5dfe93411f6c9ff85d37f1c61af932da4f4baabfb288f258e9b9a860934"

      define_method(:install) do
        bin.install "adms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/adms/releases/download/v0.0.1/adms_0.0.1_darwin_arm64.tar.gz"
      sha256 "0238f632532a8f9ae702ac9f7591d4f21a03921c63f0aa84205ee65d22e6292b"

      define_method(:install) do
        bin.install "adms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/adms/releases/download/v0.0.1/adms_0.0.1_linux_amd64.tar.gz"
      sha256 "c7bf1d5f023cd74fd38aaf1373058200fe988bf9b9a466a7dd00f65782cecc52"
      define_method(:install) do
        bin.install "adms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/adms/releases/download/v0.0.1/adms_0.0.1_linux_arm64.tar.gz"
      sha256 "42ffe2322a61fc36bd64d0c86ee1c29cd806b4361248c7b61c645df8a5dd4001"
      define_method(:install) do
        bin.install "adms"
      end
    end
  end
end
