# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTrace < Formula
  desc "Instantly visualize request flows in your Go application — no infrastructure, no code changes."
  homepage "https://github.com/mickamy/go-trace"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.5/go-trace_0.0.5_darwin_amd64.tar.gz"
      sha256 "a5756b6f88f441b29ba33f333849c7e8e10ed0216e008a09cd236db0ecb2a58d"

      define_method(:install) do
        bin.install "go-trace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.5/go-trace_0.0.5_darwin_arm64.tar.gz"
      sha256 "82944bdb44e9c1b21c783eece4ade15ebf743733a978349ced60529dd3f1a9bf"

      define_method(:install) do
        bin.install "go-trace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.5/go-trace_0.0.5_linux_amd64.tar.gz"
      sha256 "8b597b81ef248a2fe3a1832c9b8efeb81fc921903c762daf7e522cb7c1c9890a"
      define_method(:install) do
        bin.install "go-trace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/go-trace/releases/download/v0.0.5/go-trace_0.0.5_linux_arm64.tar.gz"
      sha256 "84558474dbf114a2dc7499c54e279a546001f37a2a6eadf089b458554efce216"
      define_method(:install) do
        bin.install "go-trace"
      end
    end
  end
end
