# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrpcTap < Formula
  desc "Watch gRPC traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/grpc-tap"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.6/grpc-tap_0.0.6_darwin_amd64.tar.gz"
      sha256 "bd4bd4c92e6e40ca72fd18d4ebc51893fe9c5ade738528bcdcf17b158b14bc00"

      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.6/grpc-tap_0.0.6_darwin_arm64.tar.gz"
      sha256 "9c59728ac87cd6d59dd8ee003c7bc779cad779448f4f0eb140525ffd2d169608"

      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.6/grpc-tap_0.0.6_linux_amd64.tar.gz"
      sha256 "465739f8a77aafd750582fe287d1f37ac49c62f9ed0d6633188c05f8b769b3d6"
      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/grpc-tap/releases/download/v0.0.6/grpc-tap_0.0.6_linux_arm64.tar.gz"
      sha256 "876606e2d2c3722b6ce3599f13ace8f0e457987a00848068ee7a1f963e2e1af0"
      define_method(:install) do
        bin.install "grpc-tap"
        bin.install "grpc-tapd"
      end
    end
  end
end
