# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seeder < Formula
  desc "Populate your database with realistic fake data, one command."
  homepage "https://github.com/mickamy/seeder"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.3/seeder_0.0.3_darwin_amd64.tar.gz"
      sha256 "751dddd43dfa2424438affaab8d2def678b4044f54f8aae4ce88631decbd6a13"

      define_method(:install) do
        bin.install "seeder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.3/seeder_0.0.3_darwin_arm64.tar.gz"
      sha256 "892c8df5a19364c2f827f50d6b516a97d7b8521dbd724fdba7e6f93a75db4712"

      define_method(:install) do
        bin.install "seeder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.3/seeder_0.0.3_linux_amd64.tar.gz"
      sha256 "9c2757fd6d90a8a433c84c3ea95ab2f3684a9ad3430222816763fa6af655c9d1"
      define_method(:install) do
        bin.install "seeder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.3/seeder_0.0.3_linux_arm64.tar.gz"
      sha256 "cdcffb697d86fd126f55b044904acaa594ee9b981dd9146db7d09beac9714602"
      define_method(:install) do
        bin.install "seeder"
      end
    end
  end
end
