# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seeder < Formula
  desc "Populate your database with realistic fake data, one command."
  homepage "https://github.com/mickamy/seeder"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_darwin_amd64.tar.gz"
      sha256 "2281c6cb85261f711bdebd18ef7a93bcd29a0e716fc655f7ad6658d43ec06248"

      define_method(:install) do
        bin.install "seeder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_darwin_arm64.tar.gz"
      sha256 "697b11f5e8ef3d793a2a98dcb539c1458201ec4aa0d6bf631b5ddc04bc72bbd8"

      define_method(:install) do
        bin.install "seeder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_linux_amd64.tar.gz"
      sha256 "f6fca59626fad92d55be1c6dd3664b027f7e65960ea0a2277655b7336fe10744"
      define_method(:install) do
        bin.install "seeder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/seeder/releases/download/v0.0.1/seeder_0.0.1_linux_arm64.tar.gz"
      sha256 "a63f15364644068833a3a5a060d03fd79f11302d854db588f01dcf67ad7fdf4b"
      define_method(:install) do
        bin.install "seeder"
      end
    end
  end
end
