# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SqlTap < Formula
  desc "Watch SQL traffic in real-time with a TUI"
  homepage "https://github.com/mickamy/sql-tap"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.1/sql-tap_0.3.1_darwin_amd64.tar.gz"
      sha256 "83f65d12e21663a625ecb2219ae28098c8ca51cea4c6d28866a46c443d5ddd1a"

      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.1/sql-tap_0.3.1_darwin_arm64.tar.gz"
      sha256 "fac320d318091ef6b17faed3d19bf69cddd60d5964030df407c99ddaf36b616d"

      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.1/sql-tap_0.3.1_linux_amd64.tar.gz"
      sha256 "ae6d7e70701bffe761bf8e6420253272dacae1ef4f3e36264f56eea7b3febb60"
      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/sql-tap/releases/download/v0.3.1/sql-tap_0.3.1_linux_arm64.tar.gz"
      sha256 "6faf62c0671695a3e9f66a5ac3368e3cd5e9eac80c1cc5befd8353abf6ce204a"
      define_method(:install) do
        bin.install "sql-tap"
        bin.install "sql-tapd"
      end
    end
  end
end
