# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Standin < Formula
  desc "Generate plain fixture functions from Go structs — the same code you'd write by hand, prefilled with fake data"
  homepage "https://github.com/mickamy/standin"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/standin/releases/download/v0.0.1/standin_0.0.1_darwin_amd64.tar.gz"
      sha256 "278ae02eba64f456f13bf2ea3f6286ef3772e3057a089f562fe3acc98ddb490b"

      define_method(:install) do
        bin.install "standin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/standin/releases/download/v0.0.1/standin_0.0.1_darwin_arm64.tar.gz"
      sha256 "6cd41c590ae8f291189d87bf3170993cb07183f2dc409402a14d426141ba4964"

      define_method(:install) do
        bin.install "standin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/standin/releases/download/v0.0.1/standin_0.0.1_linux_amd64.tar.gz"
      sha256 "c0c9cd175293a46855ab6f2ececc2941040f6e4eac33237b6133476a4aa32a02"
      define_method(:install) do
        bin.install "standin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/standin/releases/download/v0.0.1/standin_0.0.1_linux_arm64.tar.gz"
      sha256 "ac089b580036c4decf6fda88d85d573e91abf217292470aa4e4117af4f6a7f21"
      define_method(:install) do
        bin.install "standin"
      end
    end
  end
end
