# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subset < Formula
  desc "Clone or delete a referentially-consistent subset of your database, one command."
  homepage "https://github.com/mickamy/subset"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_darwin_amd64.tar.gz"
      sha256 "2e62b47d9f95c417ac59e190e685ab5aec6e3cf9ac62d7b59c6861bc29cdb62f"

      define_method(:install) do
        bin.install "subset"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_darwin_arm64.tar.gz"
      sha256 "519cf8bbf47f4356a3e13bab5b58b726588f8add2733df7e9873a6cbab30e39e"

      define_method(:install) do
        bin.install "subset"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_linux_amd64.tar.gz"
      sha256 "03dead8f99e7d94e17e88578d5fcaa90e6f432a992b12f0cb1f8e5e1698ca65e"
      define_method(:install) do
        bin.install "subset"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_linux_arm64.tar.gz"
      sha256 "9ec878feac3f08ceae8c21a0b21846e6cd3a7f26949d1e8fd4e89a00f5197d2f"
      define_method(:install) do
        bin.install "subset"
      end
    end
  end
end
