# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subset < Formula
  desc "Clone or delete a referentially-consistent subset of your database, one command."
  homepage "https://github.com/mickamy/subset"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_darwin_amd64.tar.gz"
      sha256 "475ef484a096c5a810e24532c9d5a2fb3f7e4e15f2461956336bcd3a500258d7"

      define_method(:install) do
        bin.install "subset"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_darwin_arm64.tar.gz"
      sha256 "77b9cbbb77f713dc0aa5452d85170b05b6c816de0334aa652dc6702097b8e0fc"

      define_method(:install) do
        bin.install "subset"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_linux_amd64.tar.gz"
      sha256 "77abc452513351fb0427f20758f5143d5994cc724d446aebac1e82e6e34d19fd"
      define_method(:install) do
        bin.install "subset"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/subset/releases/download/v0.1.0/subset_0.1.0_linux_arm64.tar.gz"
      sha256 "e587b3db4ba0d5a01b26b3da207c3f3a0626ed917cec6719f3bd5716fbf9ce9b"
      define_method(:install) do
        bin.install "subset"
      end
    end
  end
end
