# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trc < Formula
  desc "A local request tracer for Docker microservices."
  homepage "https://github.com/mickamy/trc"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/trc/releases/download/v0.0.2/trc_0.0.2_darwin_amd64.tar.gz"
      sha256 "0419612110091e85568264677d05d95a7be77d753c55d7783c6607866d90f988"

      define_method(:install) do
        bin.install "trc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/trc/releases/download/v0.0.2/trc_0.0.2_darwin_arm64.tar.gz"
      sha256 "69d9f9e90250805b6db11371df45bcb555f97cf3734db28dfa136dc7b1810ecb"

      define_method(:install) do
        bin.install "trc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/trc/releases/download/v0.0.2/trc_0.0.2_linux_amd64.tar.gz"
      sha256 "34146199bdbc634e50357e8ce3849231291af5e10388bfc133a4db48e5e137e8"
      define_method(:install) do
        bin.install "trc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/trc/releases/download/v0.0.2/trc_0.0.2_linux_arm64.tar.gz"
      sha256 "2e1fdbce80a0e41e7f05a0924ce6ef0e1ef3020eda5c683045a40ad8d12a8f67"
      define_method(:install) do
        bin.install "trc"
      end
    end
  end
end
