# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trc < Formula
  desc "A local request tracer for Docker microservices."
  homepage "https://github.com/mickamy/trc"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/trc/releases/download/v0.0.3/trc_0.0.3_darwin_amd64.tar.gz"
      sha256 "997c458ca8cbe931afdc4d5d52c5862d0863869ae4c557af90862c852f36f014"

      define_method(:install) do
        bin.install "trc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/trc/releases/download/v0.0.3/trc_0.0.3_darwin_arm64.tar.gz"
      sha256 "59141c2040f72aecb08ce6a8f4a69b75f3d22cf54e08a18b258e9ac4da652167"

      define_method(:install) do
        bin.install "trc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/trc/releases/download/v0.0.3/trc_0.0.3_linux_amd64.tar.gz"
      sha256 "ca0d6fa8649b7fb8b849cb2d0f49d8adee5589dcfd87d8db6fc237b9e19ef508"
      define_method(:install) do
        bin.install "trc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/trc/releases/download/v0.0.3/trc_0.0.3_linux_arm64.tar.gz"
      sha256 "a1f581a975cbee6fa04ad6bb0780083a6981cc0b05d546ff872dd16022adb15f"
      define_method(:install) do
        bin.install "trc"
      end
    end
  end
end
