# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tug < Formula
  desc "Replace port conflicts with stable, named URLs for Docker Compose."
  homepage "https://github.com/mickamy/tug"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/tug/releases/download/v0.0.7/tug_0.0.7_darwin_amd64.tar.gz"
      sha256 "2cd7c2c56fc168583f251aa9ed69a0a32eddddf92bcf353163f67b545fc75f59"

      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/tug/releases/download/v0.0.7/tug_0.0.7_darwin_arm64.tar.gz"
      sha256 "24045e61d8824836d65ce7273bb3d9ba65c8cada94a50f4ed79c0438da58651a"

      define_method(:install) do
        bin.install "tug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.7/tug_0.0.7_linux_amd64.tar.gz"
      sha256 "32ff688525aaf04b7b6d5a36b97bd43f96faa9ba7d084c2f6dfbac4e867eceb1"
      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.7/tug_0.0.7_linux_arm64.tar.gz"
      sha256 "6d516bfaaa7703f5abb78af20120a84df6767f8fb0f3a563f252142e98701e4b"
      define_method(:install) do
        bin.install "tug"
      end
    end
  end
end
