# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tug < Formula
  desc "Replace port conflicts with stable, named URLs for Docker Compose."
  homepage "https://github.com/mickamy/tug"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/tug/releases/download/v0.0.6/tug_0.0.6_darwin_amd64.tar.gz"
      sha256 "effe5113fa1942edaa39ed405c4322ae41f6837c65be810ba73a79b3045ae95f"

      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/tug/releases/download/v0.0.6/tug_0.0.6_darwin_arm64.tar.gz"
      sha256 "ba63b7dd22ec78e5d2a1594f343f0e74109915a4e90331d5627be1066c56d655"

      define_method(:install) do
        bin.install "tug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.6/tug_0.0.6_linux_amd64.tar.gz"
      sha256 "816d61541aad2d484ad6a90d0569c171a56736137acec1cc8b9f05ff71c9ec21"
      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.6/tug_0.0.6_linux_arm64.tar.gz"
      sha256 "db0cc2b2f29ad7f4eccb568b213fcd30a61031f212d147504f042672e5dae1e7"
      define_method(:install) do
        bin.install "tug"
      end
    end
  end
end
