# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tug < Formula
  desc "Replace port conflicts with stable, named URLs for Docker Compose."
  homepage "https://github.com/mickamy/tug"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mickamy/tug/releases/download/v0.0.8/tug_0.0.8_darwin_amd64.tar.gz"
      sha256 "1bc1f5a2b675fda569258c2a203d824681ab1c6e57926d1d7e74dbcf2722fa45"

      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mickamy/tug/releases/download/v0.0.8/tug_0.0.8_darwin_arm64.tar.gz"
      sha256 "dd3e8de7933dfec3c5fe5297b18a90ca8d47f4dc3becf3057b5ec8f32757dd40"

      define_method(:install) do
        bin.install "tug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.8/tug_0.0.8_linux_amd64.tar.gz"
      sha256 "4c61d0ead7c8cbb2173a75ad599811c727504823f77968081a26444644177bbc"
      define_method(:install) do
        bin.install "tug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mickamy/tug/releases/download/v0.0.8/tug_0.0.8_linux_arm64.tar.gz"
      sha256 "aa6447d46fffa18171cb18546e2167652db0815b61ce804ba78baa731abd5c1f"
      define_method(:install) do
        bin.install "tug"
      end
    end
  end
end
